spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/deadzq/springcloud-config-server-test
          search-paths: test1
          username: deadzq
          password: xxxx

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/